workflows:
  android-debug:
    name: Android Debug Build - Minimal
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
      java: 17
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk 