workflows:
  android-debug:
    name: Android Debug Build - Minimal
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
      java: 11  # Downgrade ke Java 11 untuk kompatibilitas dengan Gradle 7.0.2
      groups:
        - google_credentials
    scripts:
      - name: Set up Java 11
        script: |
          echo "Setting up Java 11..."
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          
      - name: Set up Android SDK
        script: |
          echo "Checking Android SDK path..."
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "ANDROID_HOME: $ANDROID_HOME"
          
          # Pastikan Android SDK path diatur dengan benar
          # Di Codemagic, Android SDK biasanya ada di /Users/builder/programs/android-sdk-macosx
          export ANDROID_SDK_ROOT=/Users/builder/programs/android-sdk-macosx
          export ANDROID_HOME=/Users/builder/programs/android-sdk-macosx
          echo "Set ANDROID_SDK_ROOT to $ANDROID_SDK_ROOT"
          echo "Set ANDROID_HOME to $ANDROID_HOME"
          
          # Verifikasi bahwa Android SDK ada
          if [ -d "$ANDROID_HOME" ]; then
            echo "✅ Android SDK directory exists"
            ls -la $ANDROID_HOME/tools || echo "No tools directory"
            ls -la $ANDROID_HOME/platform-tools || echo "No platform-tools directory"
          fi
          
      - name: Fix Resource Conflicts
        script: |
          # Tampilkan struktur direktori untuk debugging
          echo "Checking resource directories before cleanup:"
          find android/app/src/main/res -type f -name "ic_launcher*" | sort
          
          # Hapus semua file XML ic_launcher untuk mencegah konflik dengan PNG
          find android/app/src/main/res/mipmap-*/ic_launcher.xml -delete 2>/dev/null || true
          find $CM_BUILD_DIR/android/app/src/main/res/mipmap-*/ic_launcher.xml -delete 2>/dev/null || true
          
          # Hapus juga file foreground dan background yang mungkin konflik
          find android/app/src/main/res/mipmap-*/ic_launcher_foreground.* -delete 2>/dev/null || true
          find android/app/src/main/res/mipmap-*/ic_launcher_background.* -delete 2>/dev/null || true
          
          # Pastikan mipmap-anydpi-v26 tidak bermasalah (folder khusus adaptive icons)
          rm -rf android/app/src/main/res/mipmap-anydpi-v26 2>/dev/null || true
          
          echo "Resource directories after cleanup:"
          find android/app/src/main/res -type f -name "ic_launcher*" | sort
          
          echo "Removed conflicting launcher icons"
      
      - name: Build APK with Simplified Options
        script: |
          flutter clean
          flutter pub get
          
          echo "Starting APK build with simplified options..."
          flutter build apk --debug --no-shrink
          
          # Verifikasi apakah APK berhasil dibuat
          if [ -f "build/app/outputs/flutter-apk/app-debug.apk" ]; then
            echo "✅ APK build successful!"
            ls -la build/app/outputs/flutter-apk/
            
            # Rename APK with timestamp
            TIMESTAMP=$(date +"%Y%m%d%H%M")
            cp build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/DCT-CRF-Android-debug-$TIMESTAMP.apk
            echo "✅ APK renamed with timestamp: DCT-CRF-Android-debug-$TIMESTAMP.apk"
          else
            echo "❌ APK build failed!"
            
            # Coba build dengan Gradle langsung sebagai fallback
            echo "Trying direct Gradle build as fallback..."
            cd android && ./gradlew assembleDebug --stacktrace
            
            # Periksa apakah APK berhasil dibuat dengan Gradle langsung
            if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
              echo "✅ Gradle direct build successful!"
              cp app/build/outputs/apk/debug/app-debug.apk ../build/app/outputs/flutter-apk/app-debug.apk
              
              # Rename APK with timestamp
              cd .. && TIMESTAMP=$(date +"%Y%m%d%H%M")
              cp build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/DCT-CRF-Android-debug-$TIMESTAMP.apk
              echo "✅ APK renamed with timestamp: DCT-CRF-Android-debug-$TIMESTAMP.apk"
            else
              echo "❌ All build attempts failed!"
              exit 1
            fi
          fi
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - android/app/build/outputs/apk/debug/*.apk