workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17 # Updated from 11 to 17 for better compatibility
      xcode: latest
      cocoapods: default
      # Debug build without custom signing
      vars:
        PACKAGE_NAME: "com.advantage.crf" # Application ID from build.gradle
    scripts:
      - name: Set up environment
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> "$CM_BUILD_DIR/android/local.properties"
          # Print environment for debugging
          echo "Environment variables:"
          env | sort
          
      - name: Setup project
        script: |
          # Display Flutter and Java versions
          flutter --version
          java -version
          
          # Skip Gradle wrapper check since we'll create it later
          echo "Will set up Gradle wrapper in next step..."
          
          # Update dependencies - without clean to avoid removing prior setup
          flutter pub get
          
          # Check Android setup
          flutter doctor -v
      - name: Setup Gradle wrapper
        script: |
          # Check Android directory structure 
          ls -la android/
          
          # Create missing Gradle wrapper
          echo "Creating Gradle wrapper since it's missing..."
          cd android
          mkdir -p gradle/wrapper
          
          # Create gradle-wrapper.properties
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.5-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          
          # Download Gradle wrapper files
          curl -s -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.5.0/gradle/wrapper/gradle-wrapper.jar
          curl -s -o gradlew https://raw.githubusercontent.com/gradle/gradle/v7.5.0/gradlew
          curl -s -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/v7.5.0/gradlew.bat
          chmod +x gradlew
          
          # Verify setup
          ls -la gradle/wrapper/
          cat gradle/wrapper/gradle-wrapper.properties
          cd ..
          
      - name: Build APK with Flutter
        script: |
          # Use Flutter build instead of direct Gradle
          echo "Building debug APK with Flutter..."
          flutter build apk --debug
          
          # Check if APK was built with Flutter
          APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            echo "Debug build successful with Flutter. Renaming APK..."
            timestamp=$(date +"%Y%m%d%H%M")
            cp $APK_PATH build/app/outputs/flutter-apk/crf-debug-${timestamp}.apk
            echo "Created: crf-debug-${timestamp}.apk"
            ls -la build/app/outputs/flutter-apk/
          else
            echo "Flutter build failed. Trying with no-tree-shake-icons option..."
            # Try Flutter build with specific options
            flutter build apk --debug --no-tree-shake-icons
            
            # Check if second build attempt succeeded
            if [ -f "$APK_PATH" ]; then
              echo "Build successful with no-tree-shake-icons option!"
              timestamp=$(date +"%Y%m%d%H%M")
              cp $APK_PATH build/app/outputs/flutter-apk/crf-debug-${timestamp}.apk
            else
              echo "All build attempts failed. See logs for details."
            fi
          fi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/reports/
      - $HOME/.gradle/daemon
      - $HOME/.gradle/caches
      - android/gradlew.log
      - flutter_drive.log
    # Artifact publishing and notification
    publishing:
      scripts:
        - echo "Build completed successfully!"