workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9 # Using specific older version that's more compatible
      java: 11 # Downgraded Java version for compatibility
# No signing config for debug build
      vars:
        PACKAGE_NAME: "com.advantage.crf" # Application ID from build.gradle
    scripts:
      - name: Set up environment
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> "$CM_BUILD_DIR/android/local.properties"
          # Print environment for debugging
          echo "Environment variables:"
          env | sort
          
      - name: Setup project
        script: |
          # Display Flutter and Java versions
          flutter --version
          java -version
          
          # Create a dummy keystore for debug build
          keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          
          # Create a simpler gradle.properties with AndroidX settings
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "org.gradle.jvmargs=-Xmx3072m" >> android/gradle.properties
          echo "org.gradle.parallel=true" >> android/gradle.properties
          echo "org.gradle.daemon=true" >> android/gradle.properties
          
          # Clean and get dependencies
          flutter clean
          flutter pub get
          
          # Check Android setup
          flutter doctor -v
      - name: Setup Gradle wrapper
        script: |
          # Check Android directory structure 
          ls -la android/
          
          # Let Flutter create the Gradle wrapper for us
          cd android
          flutter pub get
          flutter build apk --debug --target-platform=android-arm --no-pub
          
          # Verify Gradle wrapper exists
          ls -la gradle/wrapper/ || echo "Wrapper not created yet, will be created during build"
          cd ..
          
      - name: Build APK with Flutter (Simplified)
        script: |
          # Configure Gradle
          export GRADLE_OPTS="-Dorg.gradle.project.android.useAndroidX=true -Dorg.gradle.jvmargs=-Xmx4g"
          
          # Simple direct build targeting ARM platform
          echo "Building debug APK targeting ARM platform..."
          flutter build apk --debug --target-platform=android-arm
          
          # Export the APK
          APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            # Create export directory
            mkdir -p "$FCI_EXPORT_DIR"
            timestamp=$(date +"%Y%m%d%H%M")
            cp "$APK_PATH" "$FCI_EXPORT_DIR/crf-debug-${timestamp}.apk"
            echo "APK successfully exported to: $FCI_EXPORT_DIR/crf-debug-${timestamp}.apk"
            ls -la "$FCI_EXPORT_DIR"
          else
            echo "Failed to build APK. Trying with additional flags..."
            flutter build apk --debug --target-platform=android-arm --no-shrink
            
            if [ -f "$APK_PATH" ]; then
              mkdir -p "$FCI_EXPORT_DIR"
              timestamp=$(date +"%Y%m%d%H%M")
              cp "$APK_PATH" "$FCI_EXPORT_DIR/crf-debug-${timestamp}.apk"
              echo "APK successfully exported with --no-shrink flag"
            else
              echo "All build attempts failed."
              exit 1
            fi
          fi
          
      - name: Verify and finalize artifacts
        script: |
          # List all APK files in the workspace
          echo "Searching for all APK files..."
          find . -name "*.apk" -type f | sort
          
          # Ensure we always have an APK for download regardless of name
          APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            # Create artifact directories if they don't exist
            mkdir -p "$FCI_BUILD_OUTPUT_DIR" "$FCI_EXPORT_DIR" "$FCI_ARTIFACT_ROOT"
            
            # Copy to all possible artifact locations
            cp "$APK_PATH" "$FCI_BUILD_OUTPUT_DIR/crf-debug-final.apk"
            cp "$APK_PATH" "$FCI_ARTIFACT_ROOT/crf-debug-final.apk"
            cp "$APK_PATH" "$CM_EXPORT_DIR/crf-debug-final.apk" 2>/dev/null || echo "CM_EXPORT_DIR not available"
            
            echo "APK copied to all artifact locations"
          else
            echo "No APK found to export"
          fi
    artifacts:
      - $FCI_BUILD_OUTPUT_DIR/*.apk
      - $FCI_EXPORT_DIR/*.apk
      - $FCI_ARTIFACT_ROOT/*.apk
      - build/**/outputs/**/*.apk
      
    # Empty cache configuration to prevent hanging
    cache:
      cache_paths: []