workflows:
  android-debug:
    name: Android Debug Build - Minimal
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
      java: 17
      android_sdk: /Users/builder/programs/android-sdk-macosx
      groups:
        - google_credentials
    scripts:
      - name: Set up Java 17
        script: |
          echo "Setting up Java 17..."
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          
      - name: Set up Android SDK
        script: |
          echo "Checking Android SDK path..."
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "ANDROID_HOME: $ANDROID_HOME"
          
          # Pastikan Android SDK path diatur dengan benar
          if [ -z "$ANDROID_SDK_ROOT" ]; then
            export ANDROID_SDK_ROOT=/Users/builder/programs/android-sdk-macosx
            echo "Set ANDROID_SDK_ROOT to $ANDROID_SDK_ROOT"
          fi
          
          if [ -z "$ANDROID_HOME" ]; then
            export ANDROID_HOME=/Users/builder/programs/android-sdk-macosx
            echo "Set ANDROID_HOME to $ANDROID_HOME"
          fi
          
      - name: Fix Resource Conflicts
        script: |
          # Tampilkan struktur direktori untuk debugging
          echo "Checking resource directories before cleanup:"
          find android/app/src/main/res -type f -name "ic_launcher*" | sort
          
          # Hapus semua file XML ic_launcher untuk mencegah konflik dengan PNG
          find android/app/src/main/res/mipmap-*/ic_launcher.xml -delete 2>/dev/null || true
          find $CM_BUILD_DIR/android/app/src/main/res/mipmap-*/ic_launcher.xml -delete 2>/dev/null || true
          
          # Hapus juga file foreground dan background yang mungkin konflik
          find android/app/src/main/res/mipmap-*/ic_launcher_foreground.* -delete 2>/dev/null || true
          find android/app/src/main/res/mipmap-*/ic_launcher_background.* -delete 2>/dev/null || true
          
          # Pastikan mipmap-anydpi-v26 tidak bermasalah (folder khusus adaptive icons)
          rm -rf android/app/src/main/res/mipmap-anydpi-v26 2>/dev/null || true
          
          echo "Resource directories after cleanup:"
          find android/app/src/main/res -type f -name "ic_launcher*" | sort
          
          echo "Removed conflicting launcher icons"
      
      - name: Update Gradle Wrapper
        script: |
          echo "Checking Gradle wrapper version..."
          cat android/gradle/wrapper/gradle-wrapper.properties
          
          # Pastikan menggunakan Gradle 8.0 untuk kompatibilitas dengan AGP 8.1.0
          sed -i '' 's/gradle-[0-9]\.[0-9]-all.zip/gradle-8.0-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties
          
          echo "Updated Gradle wrapper:"
          cat android/gradle/wrapper/gradle-wrapper.properties
          
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          
          echo "Starting APK build..."
          flutter build apk --debug --verbose
          
          # Verifikasi apakah APK berhasil dibuat
          if [ -f "build/app/outputs/flutter-apk/app-debug.apk" ]; then
            echo "✅ APK build successful!"
            ls -la build/app/outputs/flutter-apk/
            
            # Rename APK with timestamp
            TIMESTAMP=$(date +"%Y%m%d%H%M")
            cp build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/DCT-CRF-Android-debug-$TIMESTAMP.apk
            echo "✅ APK renamed with timestamp: DCT-CRF-Android-debug-$TIMESTAMP.apk"
          else
            echo "❌ APK build failed!"
            exit 1
          fi
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk