workflows:
  android-debug:
    name: Android Debug Build - DCT CRF
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
      java: 17
      vars:
        PACKAGE_NAME: "com.advantage.crf"
    scripts:
      - name: Set up environment
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> "$CM_BUILD_DIR/android/local.properties"
          
      - name: Fix Preview class conflict
        script: |
          # Fix QR mobile vision Preview class conflict in our code
          if [ -f "lib/widgets/qr_code_scanner_tl_widget.dart" ]; then
            echo "Fixing QR Scanner widget in our code"
            sed -i '' 's/Icons.camera_off/Icons.no_photography/g' "lib/widgets/qr_code_scanner_tl_widget.dart"
          fi
          
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          
          # Set fixed output name
          cat > /tmp/apk_name.txt << 'EOF'
    // Set a fixed name for the debug APK
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "CRF_Android_final.apk"
        }
    }
EOF
          sed -i '' -e '/applicationVariants.all/,/}/c\
'"$(cat /tmp/apk_name.txt)"'
' "android/app/build.gradle"
          
          # Build APK
          flutter build apk --debug --no-shrink
          
          # Copy to output directory
          mkdir -p "$FCI_BUILD_OUTPUT_DIR"
          cp build/app/outputs/flutter-apk/app-debug.apk "$FCI_BUILD_OUTPUT_DIR/CRF_Android_final.apk"
          
          # Set MIME type for direct download
          echo "application/vnd.android.package-archive" > "$FCI_BUILD_OUTPUT_DIR/CRF_Android_final.apk.mime"
          
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - $FCI_BUILD_OUTPUT_DIR/CRF_Android_final.apk
    
    publishing:
      email:
        recipients:
          - devs@advantage.co.id
        notify:
          success: true
          failure: true